resources:
  - name: notifications-paas-autoscaler-git
    type: git
    source:
      uri: https://github.com/alphagov/notifications-paas-autoscaler.git

jobs:
  - name: build-autoscaler
    plan:
      - get: notifications-paas-autoscaler-git
        trigger: true

      - task: run-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: python
              tag: 3.6
          inputs:
            - name: notifications-paas-autoscaler-git
          run:
            path: /bin/bash
            dir: notifications-paas-autoscaler-git
            args:
              - -euc
              - |
                  pip install -r dev_requirements.txt
                  make test
